/* eslint-disable */
// THIS IS AN AUTOGENERATED FILE.
// DON'T EDIT THIS FILE DIRECTLY.

export default [{"name":"mengenal-higher-order-function-di-javascript","date":"2019-08-19T00:00:00.000Z"},{"name":"rencana-bulan-agustus-2019","date":"2019-08-03T00:00:00.000Z"},{"name":"masa-depan","date":"2019-05-17T00:00:00.000Z"},{"name":"tak-akan-datang","date":"2019-05-07T00:00:00.000Z"},{"name":"it-fest-bersama-it-polsri","date":"2018-11-22T00:00:00.000Z"}]