export {
  PRODUCTION_URL,
  SITE_NAME,
  AUTHOR_NAME,
  AUTHOR_FULLNAME,
  EMAIL,
  FACEBOOK_USERNAME,
  TWITTER_USERNAME,
  INSTAGRAM_USERNAME,
  GITHUB_USERNAME,
  LINKEDIN_USERNAME,
  DISQUS_SHORTNAME,
  BLOG_PAGINATION_LIMIT,
  SYNTAX_HIGHLIGHTING,
  ACTIVATE_ADS
} from '../../settings.json';
